name: test
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run test
        env:
          EXTENSION_ID: ${{secrets.EXTENSION_ID}}
          JWT_ISSUER: ${{secrets.JWT_ISSUER}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}